### ISSUE TITLE
New "List of Blogs" section?

### ISSUE THREAD

**Issue by DocOtak** [cchdo/usgoship.ucsd.edu#10]
From Lynne Talley in Issue #8 
------------------------------
>I can’t figure out how to reach the set of blogs anymore though since ushydro now redirects to usgoship.

We didn't have any set of blogs on the old ushydro site. Here is my guess at what is meant:

The old ushydro site had an "Outreach" section which allowed for various tags on pages, one of these tags was "blogs". That site allowed a user to view a list of posts by tag. My guess is that this listing is what lynne is looking for.

There are two solutions to this:

1. Figure out how to view posts by category/tags (Jekyll can probably do it)
2. Include a list of blogs as a section in the Links
  a. Also maybe retitle links to be something like "Links/Blogs"
3. Include a list of blogs as a separate page distinct from the "Links" page.

Option 2 sounds nice to me...

**Comment by cberys** [comment]
Option 2 sounds fine to me, would mean more traffic to that page too since
blogs sound more inviting than links.

Tags sound nice (option 1), but that would be the most difficult to
implement and keep up to date.

**Comment by DocOtak** [comment]
Lynne,
We never really had a set of blogs, though we were tagging outreach posts which contained blogs.
Would you want to have an explicit list of blogs links on the site? If so, my recommendation would be to include the list as s section in the Links page, We could then retitle that to "Links/Blogs".

**Comment by DocOtak** [comment]
From Lynne Talley
-------------------
>HI Andrew - there was a lot of outreach information on the original site - maybe the word ‘blog’ was too narrow. I would like to ensure that all of that outreach material (which included some videos as well), is available.
>
>I think we should just have a section called  “Outreach” that goes to a page with all of those links on it. It wuld then be updated to include each new cruise as well?
>
>Can we add a slide show at the top of the page?  Or 1 image to start with, with the idea of it becoming a slide show?
>
>(Here’s the SOCCOM page, 
http://soccom.princeton.edu
>
>with its slide show, and a more traditional organization than the new GO-SHIP page, which of course isn’t necessary, just think it’s best to have some pictures.  Or if you go to one of the menu items, say, Observations, you’ll see a narrower bar at the top with a fixed photo. Perhaps that’s what we should aim for, so just expanding the current GO-SHIP logo bar to include a picture.
>
>Lynne

**Comment by DocOtak** [comment]
This will be invalidated by #22
