### ISSUE TITLE
Issues with Scheduling for I05, I07N, and S4P

### ISSUE THREAD

**Issue by DocOtak** [cchdo/usgoship.ucsd.edu#12]
Bit of an email thread going on:

Thus far there hasn't been a specific request for a change to the "Hydrotable" other than both Jim and Lynne asking that it be changed somehow (bolded bellow):

----------------------
Hi Jim/Lynne,

I'm sitting here with Dick going over GO-SHIP cruise plans.  On the US
GO-SHIP site IO5 (UNOLS)  is listed for 2018, along with IO7N (NOAA,
planned), and S4P (UNOLS). Is this correct?  This is going to cause us
severe issues regarding staffing.

Rik W.

--------
Rik,

I have been remiss in updating not only the US GO-SHIP site but also the UNOLS ship schedule requests for the future lines.  I05 will not be in 2018. I05 will probably be in 2019. One problem with it, not yet resolved, has to do with NSF asking if we could do I05 and I06S back-to-back due to the issues associated with placing a global-class ship into that part of the world. Perhaps NSF can come up with a cruise or two in that area to run between the two GO-SHIP cruises, which together sum to over 90 days. Well, I'd better get into the ship scheduling system. 

**I will ask the CCHDO staff to update the US GO-SHIP web site.**

Thanks for reminding me and for pointing this out. 

Jim

-----------

HI Jim - thank you for letting us know.  That changes my SOCCOM float planning, good to know now!

**Can we change the usgoship cruise table please, as it is misleading several of us?**

The rest of the schedule shown on usgoship is:

2018: S4P and I7N
2019: I6S, A13.5 and now I5

Also is it accurate that S4P is scheduled March - May?  There’s a lot of ice in there then. Sure would be a whole lot simpler to be run in the same time as previous two, which was Feb-April, still problems with ice.  For good reasons we should do our best to be in there the same months as the 1992 and 2011 occupations.

If the schedule really is March-May, and there’s room to push, we should do it as strongly as possible.

Lynne

**Comment by DocOtak** [comment]
From Jim Swift
---------------

Pending A13.5 (2020)
2020-March to 2020-May
NOAA

Pending I06S (2019)
2019-January to 2019-May
UNOLS

Pending I05 (2019)
2019-February to 2019-June
UNOLS

Pending P06 (2017)
2017-July to 2017-September
UNOLS

Completed P18 (2016)
2016-11-01 to 2017-01-01 (use actual cruise dates, whatever they were; JHS did not check the dates)
NOAA

**Comment by cberys** [comment]
closing issue, note:

The dates for pending US GO-SHIP cruises have been updated. We are waiting to hear official dates for P18 to update and add ExpoCode.
