### ISSUE TITLE
Site Deprecation Warning

### ISSUE THREAD

**Issue by DocOtak** [cchdo/usgoship.ucsd.edu#22]
We (Isa Rosso mostly) are in the process of migrating this over to a Scripps IT managed service. Once that occurs this repo will be archived and no longer maintained. I've asked for an ETA or some timeline, currently I can only guess that it will be "soon" in the weeks sense.

**Comment by kstocks** [comment]
We should talk. I thought the long-term was that the hydro table should integrate with the database, so it could pull core info from that. Sounds like you are planning to decouple it to be completely manually maintained?

-K


<><><><><><><><><><><><><><><><>
Karen Stocks, PhD
Director, Geological Data Center
Scripps Institution of Oceanography
+1 858-534-1898
kstocks@ucsd.edu

**Comment by DocOtak** [comment]
This repository doesn't have any code in it relating to the hydrotable other than an iframe and the legend. The hydrotable data itself was and is already completely manually maintained separately. Once the new site is running, none of this code will be in active use, though the map should (maybe) be spun off and be around for updating, depending on how they want to handle updates to it going forward.

The hydrotable display code lives in this [cchdo/hydrotable3](https://github.com/cchdo/hydrotable3). The backend was essentially separate already but made completely separate as part of the server upgrades on 2019-06-06, that code lives here [cchdo/hydrotablebackend](https://github.com/cchdo/hydrotablebackend). Though I had forgotten to push the "push" button some 17 days ago.

**Comment by DocOtak** [comment]
The "new" usgoship site is live as of 2018-08-12, this repository is no longer being used as the source.
